#pragma once

#define INT_DEFAULT_DISTR_AMOUNT 2;
#define INT_DEFAULT_FABRIC_AMOUNT 3;
#define INT_DEFAULT_MAGAZIE_AMOUNT 4;
#define INT_DEFAULT_SHOP_AMOUNT 5;

#define DOUBLE_CONTRACT_COST_DISTR 10;
#define DOUBLE_CONTRACT_COST_FABRIC 10;
#define DOUBLE_CONTRACT_COST_MAGAZINE 10;

#define INT_MIN_RANGE_OF_DISTR 3;
#define INT_MIN_RANGE_OF_FABRIC 2;
#define INT_MIN_RANGE_OF_MAGAZINE 1;
#define INT_MIN_RANGE_OF_SHOP 1;

#define INT_MAX_RANGE_OF_DISTR 5;
#define INT_MAX_RANGE_OF_FABRIC 4;
#define INT_MAX_RANGE_OF_MAGAZINE 3;
#define INT_MAX_RANGE_OF_SHOP 4;

#define INT_MIN_RANGE_OF_POWER 200
#define INT_MAX_RANGE_OF_POWER 300

#define INT_MIN_RANGE_OF_VAR_COSTS 5
#define INT_MAX_RANGE_OF_VAR_COSTS 20

#define INT_MIN_RANGE_OF_CONTRACT_COST 5
#define INT_MAX_RANGE_OF_CONTRACT_COST 10

#define INT_MIN_RANGE_OF_PROFIT 60
#define INT_MAX_RANGE_OF_PROFIT 90

#define INT_MIN_RANGE_OF_SOL 20
#define INT_MAX_RANGE_OF_SOL 30

#define INT_MIN_RANGE_OF_XD 30
#define INT_MAX_RANGE_OF_XD 40

#define INT_MIN_RANGE_OF_XF 20
#define INT_MAX_RANGE_OF_XF 30

#define INT_MIN_RANGE_OF_XM 10
#define INT_MAX_RANGE_OF_XM 20